# Generated by Django 6.0.5 on 2026-06-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping')], max_length=20),
        ),
    ]
